package cmd

import (
	"fmt"
	"os"
	"strings"

	"github.com/devenock/api-doc-gen/pkg/analyzer"
	"github.com/spf13/cobra"
)

var initCmd = &cobra.Command{
	Use:          "init",
	Short:        "Initialize configuration file",
	Long:         `Create a configuration file (.apidoc-gen.yaml) in the current directory.`,
	RunE:         runInit,
	Example:      `  api-doc-gen init`,
	SilenceUsage: true,
}

func init() {
	rootCmd.AddCommand(initCmd)
}

func runInit(cmd *cobra.Command, args []string) error {
	configPath := ".apidoc-gen.yaml"

	if _, err := os.Stat(configPath); err == nil {
		fmt.Printf("Configuration file already exists at %s\n", configPath)
		return nil
	}

	projectPath := "."
	if len(args) > 0 {
		projectPath = args[0]
	}
	detectedFrameworks := analyzer.DetectFrameworks(projectPath)
	detectedFramework := ""
	if len(detectedFrameworks) == 1 {
		detectedFramework = detectedFrameworks[0]
	}
	frameworkLine := `framework: ""`
	if detectedFramework != "" {
		frameworkLine = fmt.Sprintf(`framework: %q`, detectedFramework)
	}

	defaultConfig := fmt.Sprintf(`# API Documentation Generator Configuration
# Generated by api-doc-gen

# Output directory for generated documentation
output: ./docs

# Documentation type: swagger or postman
type: swagger

# Backend framework (optional): gin, echo, fiber, gorilla, chi
# Set by init from go.mod; leave empty for auto-detection
%s

# Directories to exclude from scanning
`, frameworkLine) + `exclude:
  - vendor
  - node_modules
  - .git
  - test
  - tests

# API base path (e.g., /api/v1)
base_path: ""

# API metadata
title: ""  # leave empty to use the go.mod module name automatically
version: "1.0.0"
description: "Auto-generated API documentation"

# Server configuration
servers:
  - url: "http://localhost:8080"
    description: "Development server"

# Auth middleware names (optional). When set, only these exact names
# (case-insensitive) mark a route group as authenticated — overrides the
# built-in "contains 'auth' or 'jwt'" heuristic entirely. Useful when that
# heuristic gets your middleware wrong, e.g. a false positive like
# "AuthorMiddleware", or a false negative like "requireSession".
# auth_middleware:
#   - requireSession
#   - JWTAuth

# Verbose output
verbose: false
`

	if err := os.WriteFile(configPath, []byte(defaultConfig), 0644); err != nil {
		return &exitCodeError{fmt.Errorf("failed to create config file: %w", err), ExitRuntimeError}
	}

	fmt.Printf("✅ Configuration file created: %s\n", configPath)
	if detectedFramework != "" {
		fmt.Printf("   Detected framework: %s (from go.mod)\n", detectedFramework)
	} else if len(detectedFrameworks) > 1 {
		fmt.Printf("   ⚠️  Multiple frameworks detected in go.mod (%s) — set \"framework\" in %s explicitly.\n",
			strings.Join(detectedFrameworks, ", "), configPath)
	}
	fmt.Println("You can now customize the configuration and run 'api-doc-gen generate'")
	return nil
}
